/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package parseURL;

import java.io.IOException;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

public class ExtendedURLParser {

    public static void getType(Work[] workList) {
        for (int i = 0; i < workList.length; i++) {
            if (workList[i].getURL().toLowerCase().contains("plays")) {
                workList[i].setType("play");
                System.out.println(workList[i].getTitle() + ": PLAY");
            } else if (workList[i].getURL().toLowerCase().contains("sonnets")) {
                workList[i].setType("sonnet");
                System.out.println(workList[i].getTitle() + ": SONNET");
            } else {
                workList[i].setType("poem");
                System.out.println(workList[i].getTitle() + ": POEM");
            }
        }
    }

    public static Work[] getWork(String url) {
        Work[] results = null;
        try {
            Document doc = Jsoup.connect(url).get();
            String title = doc.title();
            Elements links = doc.select("[class='sidebarworks']").select("a[href]");
            results = new Work[links.size()];
            for (int b = 0; b < links.size(); b++) {
                Element bElem = links.get(b);
                results[b] = new Work(bElem.text(), bElem.attr("href").toString());
            }
            return results;
        } catch (IOException e) {
            e.printStackTrace();
        }
        return results;
    }

    public static void main(String[] args) {
        String baseURL = "http://www.opensourceshakespeare.org";
        Work[] workList = getWork(baseURL);
        getType(workList);
    }
}

