/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package parseURL;

import java.io.IOException;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

public class URLParser {

    public static String getTitle(String[] workList, String phrase) {
        for (int i = 0; i < workList.length; i++) {
            if (workList[i].toLowerCase().contains("plays")) {
                System.out.println(workList[i] + ": PLAY");
            } else if (workList[i].toLowerCase().contains("sonnets")) {
                System.out.println(workList[i] + ": SONNETS");
            } else {
                System.out.println(workList[i] + ": POEM");
            }
        }
        return "";
    }

    public static String[] getWork(String url) {
        String[] results = null;
        try {
            Document doc = Jsoup.connect(url).get();
            String title = doc.title();
            Elements links = doc.select("[class='sidebarworks']").select("a[href]");
            results = new String[links.size()];
            for (int b = 0; b < links.size(); b++) {
                Element bElem = links.get(b);
                results[b] = bElem.attr("href").toString();
            }
            return results;
        } catch (IOException e) {
            e.printStackTrace();
        }
        return results;
    }

    public static void main(String[] args) {
        String baseURL = "http://www.opensourceshakespeare.org";
        String[] workList = getWork(baseURL);
        getTitle(workList,"to be or not to be");
    }
}

