version: '3'

services:
  site:
    environment:
      - JEKYLL_ENV=docker
    command: /bin/bash -c "bundle install; bundle exec jekyll serve --config  _config.yml,_config.docker.yml"
    image: jekyll/jekyll
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000